### ISSUE TITLE
Problem complete simple navigation task

### ISSUE THREAD

**Issue by chcorbato** [marioney/metacontrol_nav#3]
I have run the simple MVP (87a87ea) and the adaptation works, but after adaptation the robot does not succeed reaching the goal pose using the `safe` configuration.
See rviz screenshot where the robot gets stuck.
![rviz_screenshot_2020_05_07-13_48_01](https://user-images.githubusercontent.com/9592617/81291278-c5a34980-9069-11ea-87ea-d80762275b65.png)

**Comment by marioney** [comment]
This should be solved with the new navigation parameters in https://github.com/rosin-project/metacontrol_nav/commit/8a4c552758de638e162b8e065d6d11400cd0041f Also with the new map, it should not be a problem.

@chcorbato I'm closing this for now, but please re-open it if you still experience
